### ISSUE TITLE
Failed to load the editor-stats package

### ISSUE THREAD

**Issue by Caged** [atom/editor-stats#20]
[Enter steps to reproduce below:]

1. Close Atom
2. Open Atom

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [editor-stats](https://github.com/atom/editor-stats) package, v0.17.0

### Stack Trace

Failed to load the editor-stats package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/justin/github/editor-stats/lib/stats-tracker.coffee:4:7)
    at Object.<anonymous> (/Users/justin/github/editor-stats/lib/stats-tracker.coffee:63:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "tmp",
      "log",
      ".cache",
      ".sass-cache",
      ".bundle",
      "build",
      "compile-cache",
      "storage"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
command-logger, v0.22.0
editor-stats, v0.17.0
emmet, v2.3.4
language-liquid, v0.2.0
language-pgsql, v0.2.0
language-puppet, v0.10.0
language-r, v0.1.1
minimap, v4.5.0
script, v2.18.0

# Dev
tabs, v0.41.0
tree-view, v0.86.0
```

Hmm, didn't realize I was using a dev version of those last two packages.  apm unlink and apm uninstall didn't appear to get rid of them.

**Comment by izuzak** [comment]
@Caged I'm having trouble reproducing this. :confused: Can you still reproduce this in Atom 0.189.0?

> Hmm, didn't realize I was using a dev version of those last two packages. apm unlink and apm uninstall didn't appear to get rid of them.

Are you using `apm unlink` and `apm uninstall` with the `-d` switch? That makes them apply to dev mode.

**Comment by Caged** [comment]
This appears to work now.  Thanks, @izuzak!
